### ISSUE TITLE
eureka集群咋配置啊？

### ISSUE THREAD

**Issue by zhaiyuyong** [ggj2010/springcloudsamples-ggj#1]
eureka集群咋配置啊？

**Comment by ggj2010** [comment]
官网文档参考地址：http://cloud.spring.io/spring-cloud-static/docs/1.0.x/spring-cloud.html#_peer_awareness

---

spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2/eureka/

---

spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1/eureka/
