### ISSUE TITLE
我最近开始学习springcloud，这个可以作为入门项目学习吗？

### ISSUE THREAD

**Issue by slgxmh** [ggj2010/springcloudsamples-ggj#2]

**Comment by ggj2010** [comment]
建议先看下springboot，然后再学习springcloud

**Comment by slgxmh** [comment]
是学习了springboot，准备开始学习springcloud了，想找个springcloud项目看看

**Comment by ggj2010** [comment]
给你推荐一个人的博客 可以了解一些概念http://blog.csdn.net/liaokailin/article/category/6212338
